import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home, Package, BarChart3, Settings, Plus, Check, Clock3, ChevronRight, Sparkles, Pill, ShoppingBag} from 'lucide-react';
import './styles.css';
import './avatar.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
type Item={schedule_id:number;medication_id:number;name:string;quantity:number;taken:boolean;at:string};
type Today={date:string;groups:Record<string,Item[]>};
async function api(path:string, options:RequestInit={}){const tg=(window as any).Telegram?.WebApp; const headers:any={'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''}; const r=await fetch(API+path,{...options,headers:{...headers,...options.headers}}); if(!r.ok) throw new Error(await r.text()); return r.json();}
function App(){
 const [tab,setTab]=useState('today'); const [today,setToday]=useState<Today>({date:new Date().toISOString(),groups:{}}); const [meds,setMeds]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const tgUser=(window as any).Telegram?.WebApp?.initDataUnsafe?.user; const firstName=tgUser?.first_name||'Alex'; const photoUrl=tgUser?.photo_url;
 const load=()=>Promise.all([api('/today'),api('/medications')]).then(([a,b])=>{setToday(a);setMeds(b)}).catch(()=>{});
 useEffect(()=>{(window as any).Telegram?.WebApp?.ready();load()},[]);
 const greeting=useMemo(()=>{const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'},[]);
 async function takeAll(period:string){setBusy(true);try{const r=await api('/today/take-all?period='+encodeURIComponent(period),{method:'POST'});setNotice(r.message+' ✦');await load();setTimeout(()=>setNotice(''),2500)}catch(e:any){setNotice(e?.message||'Could not save')}finally{setBusy(false)}}
 const date=new Date(today.date); const pretty=date.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}); const all=Object.values(today.groups).flat(); const done=all.filter(x=>x.taken).reduce((n,x)=>n+x.quantity,0), total=all.reduce((n,x)=>n+x.quantity,0); const progress=total?Math.round(done/total*100):0;
 return <div className="app"><header><div className="eyebrow"><span className="dot"/> PRIVATE WELLNESS</div><div className="topline"><div><h1>{tab==='today'?<>{greeting}, <span>♥</span></>:tab==='cabinet'?'Your cabinet':tab==='history'?'Your progress':'Settings'}</h1><p>{tab==='today'?pretty:`${firstName}'s calm routine.`}</p></div><div className="avatar">{photoUrl?<img src={photoUrl} alt={firstName}/>:firstName.charAt(0).toUpperCase()}</div></div></header>
 {notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 <main>{tab==='today'?<TodayView groups={today.groups} progress={progress} busy={busy} onTake={takeAll}/>:tab==='cabinet'?<Cabinet meds={meds} onAdded={load}/>:tab==='history'?<History/>:<SettingsView/>}</main>
 <nav>{[['today',Home,'Today'],['cabinet',Package,'Cabinet'],['history',BarChart3,'History'],['settings',Settings,'More']].map(([id,I,label]:any)=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I size={20}/><small>{label}</small></button>)}</nav></div>
}
function TodayView({groups,progress,busy,onTake}:{groups:Record<string,Item[]>;progress:number;busy:boolean;onTake:(p:string)=>void}){const order=['Morning','Afternoon','Evening','Night'];return <><section className="hero"><div><div className="label">TODAY'S RHYTHM</div><strong>{progress}%</strong><p>{progress===100?'Everything taken care of.':progress?'You are on your way.':'A gentle start to your day.'}</p></div><div className="ring" style={{'--progress':progress} as any}><span>{progress}<i>%</i></span></div></section><div className="section-head"><h2>Today's schedule</h2><span>{Object.values(groups).flat().filter(x=>x.taken).length}/{Object.values(groups).flat().length}</span></div>{order.map(period=>groups[period]?.length?<section className="dose-card" key={period}><div className="dose-title"><div className={'period '+period.toLowerCase()}><Clock3 size={15}/>{period}</div><span>{groups[period][0].at}</span></div>{groups[period].map(x=><div className="med-row" key={x.schedule_id}><div className={'pill-icon '+(x.taken?'complete':'')}><Pill size={17}/></div><div><b>{x.name}</b><small>{x.quantity} {x.quantity===1?'pill':'pills'}</small></div>{x.taken?<Check className="taken" size={19}/>:<button className="take-one" onClick={()=>onTake(period)}>Take</button>}</div>)}<button className="primary" disabled={busy||groups[period].every(x=>x.taken)} onClick={()=>onTake(period)}>{groups[period].every(x=>x.taken)?<><Check size={18}/>All done</>:<><Check size={18}/>I took my {period.toLowerCase()} pills</>}</button></section>:null)}{!order.some(x=>groups[x]?.length)&&<div className="empty"><Sparkles size={28}/><h2>Your cabinet is ready</h2><p>Add your first medication to build a calm, reliable routine.</p></div>}</>}
function Cabinet({meds,onAdded}:{meds:any[];onAdded:()=>void}){const [open,setOpen]=useState(false);const [selected,setSelected]=useState<any>(null);const [name,setName]=useState('');const [qty,setQty]=useState('');const [period,setPeriod]=useState('Morning');const [at,setAt]=useState('08:00');const [dose,setDose]=useState('1'); async function add(){if(!name)return;await api('/medications',{method:'POST',body:JSON.stringify({name,inventory:Number(qty)||0})});setName('');setQty('');setOpen(false);onAdded()} async function buy(amount:number){if(!selected)return;await api(`/inventory/${selected.id}/purchase`,{method:'POST',body:JSON.stringify({quantity:amount})});setSelected(null);onAdded()} async function addRoutine(){if(!selected)return;await api(`/medications/${selected.id}/schedules`,{method:'POST',body:JSON.stringify({period,at:`${at}:00`,quantity:Number(dose)||1,reminder_enabled:true})});setSelected(null);onAdded()}return <><div className="cabinet-banner"><Package size={25}/><div><b>Medication cabinet</b><p>Keep your routine in view.</p></div><button onClick={()=>setOpen(true)}><Plus size={18}/></button></div>{meds.map(m=><button className="inventory-card" key={m.id} onClick={()=>setSelected(m)}><div className="med-mark"><Pill size={20}/></div><div className="inv-main"><b>{m.name}</b><small>{m.inventory} pills · {m.schedules?.length||0} routines</small></div><ChevronRight size={18}/></button>)}{!meds.length&&<div className="empty"><ShoppingBag size={28}/><h2>Nothing here yet</h2><p>Your medications will appear here.</p></div>}{open&&<div className="modal"><div className="sheet"><h2>Add medication</h2><input placeholder="Medication name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Current pills" type="number" value={qty} onChange={e=>setQty(e.target.value)}/><button className="primary" onClick={add}>Add to cabinet</button><button className="cancel" onClick={()=>setOpen(false)}>Cancel</button></div></div>}{selected&&<div className="modal"><div className="sheet"><h2>{selected.name}</h2><p className="stock">{selected.inventory} pills available</p>{selected.schedules?.map((s:any)=><div className="routine-row" key={s.id}><span>{s.period} · {s.at}</span><b>×{s.quantity}</b></div>)}<h3>Set a routine</h3><div className="routine-fields"><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Night</option></select><input type="time" value={at} onChange={e=>setAt(e.target.value)}/><input type="number" min="1" value={dose} onChange={e=>setDose(e.target.value)}/></div><button className="primary" onClick={addRoutine}>Save routine</button><div className="quick-buy"><button onClick={()=>buy(10)}>+10 pills</button><button onClick={()=>buy(20)}>+20 pills</button><button onClick={()=>buy(30)}>+30 pills</button></div><button className="cancel" onClick={()=>setSelected(null)}>Close</button></div></div>}</>}
function History(){return <div className="empty"><BarChart3 size={30}/><h2>Your story starts here</h2><p>Once you begin tracking, your gentle progress will show up here.</p></div>}
function SettingsView(){return <div className="settings"><div className="setting"><div><b>Timezone</b><small>Used for reminders and daily progress</small></div><span>Local time</span></div><div className="setting"><div><b>Reminders</b><small>Notifications follow your schedule</small></div><span className="switch on"/></div><p className="privacy">Your cabinet is private to you and your trusted Telegram account.</p></div>}
createRoot(document.getElementById('root')!).render(<App/>);
